### ISSUE TITLE
.gitignore encoding is UTF-16 LE from `gibo dump`

### ISSUE THREAD

**Issue by kubosho** [simonwhitaker/gibo#34]
## My environment

- OS: Windows 10
- Shell: PowerShell (Not use WSL)
- Git version: 2.20.1.windows.1

## Expected

.gitignore file encoding is UTF-8 from `gibo dump`

## Actual

.gitignore file encoding is UTF-16 LE from `gibo dump`

## Reproduce

1. `scoop install gibo`
2. Run `gibo dump Node Windows >> .gitignore` on any directory

## Screenshot

![gitignore](https://user-images.githubusercontent.com/430267/50385257-0f5def00-0716-11e9-95ee-eced82a30d53.PNG)

**Comment by simonwhitaker** [comment]
Thanks for reporting this!

It seems that this is expected behaviour, since UTF-16 is the default output encoding in Powershell. You can have Powershell commands output a different encoding (e.g. UTF-8) [via the $PSDefaultParameterValues preference variable](https://stackoverflow.com/questions/40098771/changing-powershells-default-output-encoding-to-utf-8).

**Comment by kubosho** [comment]
Thanks response. I will change PowerShell default encoding.
